site_name: Taller de Git
site_author: "Sergio Gómez <sergio@uco.es>"
site_description: "Curso básico de git"
repo_name: "aulasoftwarelibre/taller-de-git"
repo_url: "https://github.com/aulasoftwarelibre/taller-de-git.git"

theme:
  name: "material"
  language: "es"
  favicon: "images/logoasl.png"
extra_css: [extra.css]
extra:
  palette:
    primary: "green"
    accent: "light green"
  social:
    - type: "github"
      link: "https://github.com/aulasoftwarelibre"
    - type: "twitter"
      link: "https://twitter.com/aulasl"
    - type: "facebook"
      link: "https://facebook.com/aulasl"
    - type: "instagram"
      link: "https://instagram.com/aulasoftwarelibre"
  feature:
    tabs: true

markdown_extensions:
  - footnotes: ~
  - admonition: ~
  - pymdownx.details: ~
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - def_list: ~
  - mdx_inline_graphviz: ~

nav:
  - Inicio: index.md
  - Sistemas de control de versiones: cvs.md
  - Introducción a Git: introduccion.md
  - Aspectos básicos de Git: git.md
  - Uso básico: usobasico.md
  - Uso avanzado: usoavanzado.md
  - Ramas: ramas.md
  - Github: github.md
  - Github avanzado: github-avanzado.md
  - Comandos de git: commands.md
  - Flujo de trabajo con Git (git flow): gitflow.md
  - Referencias: referencias.md

google_analytics:
  - "UA-51754922-1"
  - "auto"
