site_name: Taller de Git
site_author: 'Sergio Gómez <sergio@uco.es>'
site_description: 'Curso básico de git'
site_favicon: 'images/logoasl.png'
repo_name: 'aulasoftwarelibre/taller-de-git'
repo_url: 'https://github.com/aulasoftwarelibre/taller-de-git.git'

theme: 'material'
extra_css: [extra.css]
extra:
  language: 'es'
  palette:
    primary: 'green'
    accent: 'light green'
  social:
    - type: 'github'
      link: 'https://github.com/aulasoftwarelibre'
    - type: 'twitter'
      link: 'https://twitter.com/aulasl'
    - type: 'facebook'
      link: 'https://facebook.com/aulasl'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
pages:
    - Inicio: index.md
    - Sistemas de control de versiones: cvs.md
    - Introducción a Git: introduccion.md
    - Aspectos básicos de Git: git.md
    - Uso básico: usobasico.md
    - Uso avanzado: usoavanzado.md
    - Ramas: ramas.md
    - Github: github.md
    - Github avanzado: github-avanzado.md
    - Flujo de trabajo con Git (git flow): gitflow.md
    - Referencias: referencias.md
google_analytics:
  - 'UA-51754922-1'
  - 'auto'
